### ISSUE TITLE
Can we have a different color for read and write occurrences?

### ISSUE THREAD

**Issue by Redsandro** [hax/refactor#18]
The highlighting is very convenient, even if you don't want to refactor.
I was wondering if it's possible to have a different highlight style for read (e.g. green) and write (e.g. red) occurrences?

**Comment by hax** [comment]
The new version has implemented this idea.
Note: it need language packages give the information of references. Up to now only latest js-refactor support this.

**Comment by Redsandro** [comment]
@hax I would like to have a read and write occurance highlight, not just an underline. This makes it quicker to spot. Is there a way I can configure this?

**Comment by hax** [comment]
@Redsandro You can customize it in your stylesheet (menu Atom->stylesheet...). See https://github.com/hax/refactor/blob/master/styles/refactor.less#L15-L23 for current styles.

To add highlight like old version, just:

``` less
  .refactor-ref .region,
  .refactor-mut .region,
  .refactor-decl .region {
      border-radius: 2px;
      box-sizing: border-box;
      background-color: rgba(54, 175, 144, 0.2);
      border: 1px solid rgba(54, 175, 144, 0.3);
  }
```
